name: Data Collection CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Build with token
      run: |
        # 替换index.html中的特殊标记为实际Token
        sed -i "s/__GH_DATA_TOKEN__/${{ secrets.GH_DATA_COLLECTION_TOKEN }}/g" index.html

        npm install
        npm run build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
